log: run test only in unix
Windows needs some enforcement to move open file.

--- FAIL: TestRotatableFile (0.00s)
    rotate_test.go:36: rename C:\Users\RUNNER~1\AppData\Local\Temp\test-rotate-1315578108/0.log C:\Users\RUNNER~1\AppData\Local\Temp\test-rotate-1315578108/1.log: The process cannot access the file because it is being used by another process.
FAIL