cmd/forwarder: do not print command errors in main
This prevents the error being printed twice like in the example below.

2023/03/22 12:19:08 [proxy] INFO: using direct proxy
2023/03/22 12:19:08 [proxy] INFO: localhost proxying mode: deny
2023/03/22 12:19:08 [api] INFO: HTTP server listen address=127.0.0.1:10000 protocol=http
Error: failed to open listener on address 31121422145: listen tcp: address 31121422145: missing port in address
failed to open listener on address 31121422145: listen tcp: address 31121422145: missing port in address
exit status 1