mk: update-devel-image add --network host
This enabled building in rootful podman.
Otherwise we hit this error

Error: building at STEP "RUN apk add --no-cache bash bash-completion ca-certificates curl jq": setup network: pasta failed with exit code 1:
Don't run as root. Changing to nobody...
No routable interface for IPv6: IPv6 is disabled
Couldn't open network namespace /proc/171325/ns/net: Permission denied